"""delete user's url columns

Revision ID: 84c923437bd1
Revises: fa8dce0dfef2
Create Date: 2024-09-14 13:07:24.714030

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84c923437bd1'
down_revision: Union[str, None] = 'fa8dce0dfef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'asker_url')
    op.drop_column('users', 'page_url')
    op.drop_column('users', 'menu_msg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('menu_msg_id', sa.BIGINT(), nullable=False))
    op.add_column('users', sa.Column('page_url', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('asker_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
