"""First migration

Revision ID: fa8dce0dfef2
Revises: 
Create Date: 2024-09-10 21:30:14.024075

"""
from datetime import date
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa8dce0dfef2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions') as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.BigInteger(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('solution_author_fk', 'users', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.add_column(sa.Column('created', sa.Date(), nullable=False, server_default=str(date.min)))
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False, server_default='-'))
        batch_op.add_column(sa.Column('fav_group_id', sa.Integer(), nullable=True))
        batch_op.alter_column('menu_msg_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'menu_msg_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    op.drop_column('users', 'fav_group_id')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'solutions', type_='foreignkey')
    op.drop_column('solutions', 'created')
    op.drop_column('solutions', 'author_id')
    # ### end Alembic commands ###
